name: chat_storage
description: Chat storage
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  words_api:
    path: ../words_api

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  very_good_analysis: ^3.0.0
